<?php

namespace Telecontact\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{

	public function getFreeContactsCount()
	{
		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();
		$qb->select('count(contact.id)');
		$qb->from('TelecontactContactBundle:contact', 'contact');
		$qb->where('contact.locked = 0');
		$qb->andWhere('contact.state in (0,1,2,3,4,5)');
		$count = $qb->getQuery()->getSingleScalarResult();
		return (int)$count;
	}


}
