<?php

namespace Telecontact\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{

	public function getFreeContactsCount()
	{
		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();
		$qb->select('count(contact.id)');
		$qb->from('TelecontactContactBundle:contact', 'contact');

		$count = $qb->getQuery()->getSingleScalarResult();
		return (int)$count;
	}
}
