<?php

namespace Telecontact\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{

	public function getFreeContactsCount()
	{
		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();
		$qb->select('count(contact.id)');
		$qb->from('TelecontactContactBundle:contact', 'contact');
		$qb->where('contact.locked = 0');
		$qb->andWhere('contact.status NOT IN (5,1)');
		$count = $qb->getQuery()->getSingleScalarResult();
		return (int)$count;
	}

	public function  getFreeContact()
	{
		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();
		$qb->select('contact');
		$qb->from('TelecontactContactBundle:contact', 'contact');
		$qb->where('contact.locked = 0');
		$qb->andWhere('contact.status <> 5');
		$qb->setFirstResult(rand(0, $this->getFreeContactsCount() - 1));
		$qb->setMaxResults(1);


		$contact = $qb->getQuery()->getSingleResult();

		return $contact;
	}


}
