services:
    sonata.admin.post:
        class: Telecontact\ContactBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Contacts" }
        arguments:
            - ~
            - Telecontact\ContactBundle\Entity\Contact
            - ~
        calls:
            - [ setTranslationDomain, [TelecontactContactBundle]]