telecontact_contact_homepage:
    pattern:  /
    defaults: { _controller: TelecontactContactBundle:Default:index }

telecontact_rest:
    prefix: /rest
    type:   rest
    resource: Telecontact\ContactBundle\Controller\RestController
